version: "3"

services:
  frontend:
    container_name: "frontend-container"
    build: ./frontend
    ports:
      - 4200:4200

  backend:
    container_name: "backend-container"
    build: ./backend
    ports:
      - 8080:8080
    depends_on:
      - database

  database:
    restart: always
    container_name: "database-container"
    build: ./database
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: dev
    volumes:
      - dbvol:/var/lib/postgresql/data
      - ./database/forDocker/db/initdb:/docker-entrypoint-initdb.d

# volumes:これ正しく設定できてる？

volumes:
  dbvol:
